version: 1.0
name: prime

download_urls:
  - /home/ankdesh/explore/ludwig/try/prime

train_filenames: test_prime.csv
#test_filenames: test_prime.csv

description: PRIME dataset 

columns:
  - name: area
    type: number
output_features:
  - name: runtime
    type: number

loader: prime.PRIMELoader
